# Generated by Django 3.2.16 on 2023-02-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('creator', models.CharField(help_text='创建人', max_length=150, verbose_name='创建人')),
                ('modifier', models.CharField(help_text='最后修改人', max_length=150, verbose_name='最后修改人')),
                ('username', models.CharField(help_text='用户名', max_length=255, verbose_name='用户名')),
                ('password', models.CharField(help_text='密码(加密)', max_length=255, verbose_name='密码(加密)')),
                ('host', models.CharField(help_text='域名或IP', max_length=255, verbose_name='域名或IP')),
                ('port', models.IntegerField(help_text='端口', verbose_name='端口')),
                ('device_type', models.PositiveSmallIntegerField(choices=[(0, '阿里云ECS'), (1, '腾讯云ECS'), (2, 'Raspberry Pi(树莓派)')], default=0, help_text='设备类型', verbose_name='设备类型')),
                ('device_status', models.PositiveSmallIntegerField(choices=[(0, '离线'), (1, '在线')], default=0, help_text='设备状态', verbose_name='设备状态')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'db_table': 'device',
            },
        ),
    ]
