# Generated by Django 3.2.18 on 2023-03-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_deployed_agent',
            field=models.BooleanField(default=False, help_text='是否已部署agent', verbose_name='是否已部署agent'),
        ),
    ]
