# Generated by Django 3.2.18 on 2023-03-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_device_is_deployed_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_status',
            field=models.PositiveSmallIntegerField(choices=[(0, '离线'), (1, '在线')], db_index=True, default=0, help_text='设备状态', verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '阿里云ECS'), (1, '腾讯云ECS'), (2, 'Raspberry Pi(树莓派)')], db_index=True, default=0, help_text='设备类型', verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='device',
            name='host',
            field=models.CharField(db_index=True, help_text='域名或IP', max_length=255, verbose_name='域名或IP'),
        ),
        migrations.AlterField(
            model_name='device',
            name='username',
            field=models.CharField(db_index=True, help_text='用户名', max_length=255, verbose_name='用户名'),
        ),
    ]
