version: "3.8"

services:
  db:
    image: mysql:8.0.30
    container_name: db
    command: --authentication_policy=*
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - /var/lib/mysql_8:/var/lib/mysql
    ports:
      - "3316:3306"
    restart: always
    tty: true
    stdin_open: true

  backend:
    build: .
    container_name: backend
    # 将django后端收集到的静态文件持久化到本地，供nginx部署时使用
    volumes:
      - ./static:/root/sugar/static
      - ./logs:/root/sugar/logs
    depends_on:
      - db
    ports:
      - "8010:8000"
    restart: always
    tty: true
    stdin_open: true

  frontend:
    build: sugar-web
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static:/app/static
      - ./sugar-web/nginx.conf:/etc/nginx/nginx.conf
      - ./sugar-web/nginx_logs:/var/log/nginx
    restart: always
    depends_on:
      - backend
    tty: true
    stdin_open: true