# Generated by Django 3.2.16 on 2023-02-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/brave.png', help_text='头像', upload_to='avatars/', verbose_name='头像'),
        ),
    ]
