# Generated by Django 3.2.18 on 2023-03-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(db_index=True, help_text='名称', max_length=128, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='title',
            field=models.CharField(db_index=True, help_text='权限名称', max_length=64, unique=True, verbose_name='权限名称'),
        ),
    ]
