# Generated by Django 3.2.18 on 2023-03-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskresult',
            name='task_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '采集设备性能数据'), (1, '向设备部署性能采集agent程序')], default=0, help_text='任务类型', verbose_name='任务类型'),
        ),
    ]
