# Generated by Django 3.2.18 on 2023-03-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20230305_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskresult',
            name='traceback',
            field=models.TextField(blank=True, default='', help_text='任务执行异常时的堆栈信息', verbose_name='Task Traceback'),
        ),
    ]
