# Generated by Django 3.2.18 on 2023-03-06 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_taskresult_traceback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskresult',
            old_name='task_id',
            new_name='task_uuid',
        ),
    ]
