# Generated by Django 3.2.18 on 2023-03-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_rename_task_id_taskresult_task_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskresult',
            name='task_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'PENDING'), (1, 'RECEIVED'), (2, 'STARTED'), (3, 'SUCCESS'), (4, 'FAILURE'), (5, 'REVOKED'), (6, 'RETRY'), (7, 'IGNORED'), (8, 'Queued')], db_index=True, default=0, help_text='任务状态', verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='taskresult',
            name='task_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '采集设备性能数据'), (1, '向设备部署性能采集agent程序')], db_index=True, default=0, help_text='任务类型', verbose_name='任务类型'),
        ),
    ]
