# Generated by Django 3.2.18 on 2023-03-12 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='followers',
            field=models.ManyToManyField(blank=True, help_text='关注人', to=settings.AUTH_USER_MODEL, verbose_name='关注人'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='父工作项', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm.workitem', verbose_name='父工作项'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='sprint',
            field=models.ForeignKey(blank=True, help_text='所属迭代', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm.sprint', verbose_name='所属迭代'),
        ),
        migrations.AddField(
            model_name='userfile',
            name='work_item',
            field=models.ForeignKey(blank=True, help_text='所属工作项', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm.workitem', verbose_name='所属工作项'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='project',
            field=models.ForeignKey(blank=True, help_text='所属项目', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm.project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='项目成员', to=settings.AUTH_USER_MODEL, verbose_name='项目成员'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='父评论', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm.comment', verbose_name='父评论'),
        ),
        migrations.AddField(
            model_name='comment',
            name='work_item',
            field=models.ForeignKey(blank=True, help_text='所属工作项', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm.workitem', verbose_name='所属工作项'),
        ),
        migrations.AddField(
            model_name='changelog',
            name='work_item',
            field=models.ForeignKey(blank=True, help_text='所属工作项', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm.workitem', verbose_name='所属工作项'),
        ),
    ]
