# Generated by Django 3.2.16 on 2023-02-16 23:54

from django.db import migrations, models
import pm.models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(help_text='用户上传的静态文件', upload_to=pm.models.user_directory_path, verbose_name='用户上传的静态文件'),
        ),
    ]
