# Generated by Django 3.2.16 on 2023-02-25 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0003_alter_changelog_changelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='status',
            new_name='project_status',
        ),
        migrations.RenameField(
            model_name='sprint',
            old_name='status',
            new_name='sprint_status',
        ),
        migrations.RenameField(
            model_name='workitem',
            old_name='status',
            new_name='work_item_status',
        ),
    ]
