# Generated by Django 3.2.16 on 2023-02-25 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0004_auto_20230225_0611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workitem',
            old_name='type',
            new_name='work_item_type',
        ),
    ]
