# Generated by Django 3.2.18 on 2023-03-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0005_rename_type_workitem_work_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_index=True, help_text='项目名称', max_length=64, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.CharField(db_index=True, help_text='负责人', max_length=150, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已完成')], db_index=True, default=0, help_text='项目状态', verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='name',
            field=models.CharField(db_index=True, help_text='迭代名称', max_length=64, verbose_name='迭代名称'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='owner',
            field=models.CharField(db_index=True, help_text='负责人', max_length=150, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='sprint_status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已完成')], db_index=True, default=0, help_text='迭代状态', verbose_name='迭代状态'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='bug_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '功能问题'), (1, '性能问题'), (2, '接口问题'), (3, '安全问题'), (4, 'UI界面问题'), (5, '易用性问题'), (6, '兼容问题'), (7, '数据问题'), (8, '逻辑问题'), (9, '需求问题')], db_index=True, help_text='缺陷类型', null=True, verbose_name='缺陷类型'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='name',
            field=models.CharField(db_index=True, help_text='工作项名称', max_length=64, verbose_name='工作项名称'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='owner',
            field=models.CharField(db_index=True, help_text='负责人', max_length=150, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, '最低'), (1, '较低'), (2, '普通'), (3, '较高'), (4, '最高')], db_index=True, help_text='优先级', verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='process_result',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '不予处理'), (1, '延期处理'), (2, '外部原因'), (3, '需求变更'), (4, '转需求'), (5, '挂起'), (6, '设计如此'), (7, '重复缺陷'), (8, '无法重现')], db_index=True, help_text='缺陷处理结果', null=True, verbose_name='缺陷处理结果'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='severity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '保留'), (1, '建议'), (2, '提示'), (3, '一般'), (4, '严重'), (5, '致命')], db_index=True, help_text='缺陷严重程度', null=True, verbose_name='缺陷严重程度'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='work_item_status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未开始'), (1, '待处理'), (2, '重新打开'), (3, '进行中'), (4, '实现中'), (5, '已完成'), (6, '修复中'), (7, '已实现'), (8, '关闭'), (9, '已修复'), (10, '已验证'), (11, '已拒绝')], db_index=True, default=0, help_text='状态', verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='work_item_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '需求'), (1, '任务'), (2, '缺陷')], db_index=True, help_text='工作项类型', verbose_name='工作项类型'),
        ),
    ]
